# URL de conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_course
# Usuário do postgres
spring.datasource.username=postgres
# Senha do postgres
spring.datasource.password=12345678
# Criar o banco de forma não contextual para evitar problemas de versão do Postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Indica que irá atualizar o banco de dados
spring.jpa.hibernate.ddl-auto=update
# Log do SQL
spring.jpa.show-sql=true
# Formatar o SQL
spring.jpa.properties.hibernate.format_sql=true
# Usado apenas se estiver utiilizando autenticação com JWT
jwt.secret=MYJWTSECRET
jwt.expiration=3600000