# Nome da aplicação.
spring.application.name=course
# Qual perfil está sendo usado.
spring.profiles.active=prod
# Permite que o jackson na hora de serializar o Json e faz com que ele traga os
# dados do OneToMany, acionando o banco de dados no fim do ciclo de vida para trazer
# o restante dos dados.
spring.jpa.open-in-view=true