# URL do banco de dados
spring.datasource.url=jdbc:postgresql://dpg-d8g7ol58nd3s739b1oqg-a.ohio-postgres.render.com/course_javasb_5uiv
# Usuário
spring.datasource.username=course_javasb_5uiv_user
# Senha
spring.datasource.password=aNsrHDzh2TAKlTjpmcxIc9PM6txtZcEw

# O JPA não deverá fazer nada
spring.jpa.hibernate.ddl-auto=none
#Não se mostra log de SQL em banco de produção
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false