# DATASOURCE
# Driver do H2
spring.datasource.driverClassName=org.h2.Driver
# Link do banco de dados e mem significa que o banco é salvo na memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 CLIENT
# Indica se o console está ativo
spring.h2.console.enabled=true
# Indica o caminho para acessar o console de admin pelo navegador
spring.h2.console.path=/h2-console
# JPA, SQL
# Dialect do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Faz com que a inicialização do banco ocorra depois de o JPA/Hibernate terminar de criar ou atualizar o schema.
spring.jpa.defer-datasource-initialization=true
# Mostra o comando que foi executado pelo JPA
spring.jpa.show-sql=true
# Formata o SQL para torna-lo mais legível
spring.jpa.properties.hibernate.format_sql=true